#!/bin/bash
if [ -d $1 ]; then
	peso=$(du $1 2> /dev/null | awk {'print $1'})
	lista=$(du -a $1 2> /dev/null)
	aya=0
	for lst_aux in $lista
	do
		if [ $aya == 0 ]; then
			p_arc=$(($lst_aux * 100 / $peso))
			cont=0
			echo -n '('
                	while [ $cont -le $p_arc ]; do
                        	echo -n "#"
                        	cont=$(( $cont + 1 ))
                	done
                	echo -n ')'$p_arc%
			aya=1
		else
			echo -e "\t"$lst_aux
			aya=0
		fi
	done
fi
