#!/bin/bash
echo "Ingrese el directorio del archivo"
read A
B=$(ls -l $A)
permisos=`echo $B | cut -d " " -f 1`
usuario=`echo $B | cut -d " " -f 3`
grupo=`echo $B | cut -d " " -f 4`

echo "permisos: "+$permisos
echo "usuario: "$usuario
echo "grupo: "$grupo
echo $A
